[package]
name = "aegis_ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aegis_core = { path = "../aegis_core" }
aegis_render = { path = "../aegis_render" }
tracing.workspace = true
windows.workspace = true
