[package]
name = "aegis_render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aegis_core = { path = "../aegis_core" }
aegis_css = { path = "../aegis_css" }
aegis_layout = { path = "../aegis_layout" }
tracing.workspace = true
