[package]
name = "flxtra_css"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
flxtra_core = { path = "../flxtra_core" }

cssparser.workspace = true
selectors.workspace = true
tracing.workspace = true
serde.workspace = true
