[package]
name = "flxtra_js"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
flxtra_core = { path = "../flxtra_core" }

tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
parking_lot.workspace = true
dashmap.workspace = true
