[package]
name = "flxtra_layout"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
flxtra_core = { path = "../flxtra_core" }
flxtra_css = { path = "../flxtra_css" }
flxtra_html = { path = "../flxtra_html" }
tracing.workspace = true
serde.workspace = true
