[package]
name = "aegis_css"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aegis_core = { path = "../aegis_core" }

cssparser.workspace = true
selectors.workspace = true
tracing.workspace = true
serde.workspace = true
